name: My First Workflow

# trigger (on event)
on:
- push

#jobs in the workflow
jobs:
  #job name
  my-first-workflow:
  #OS that this job will be running on
    runs-on: ubuntu-latest

    #list of steps to perform the task
    steps:
    - name: echo the date
      run: echo "The current time and date in GitHub is $(date)"
    - name: echo information about the context
      run: echo "head_ref - ${{github.head_ref}} - ${{github.repository_owner}}"
    - name: Echo my secret
      run: echo "MY_SECRET is ${{secrets.MY_SECRET}}"
    - name: List my current directory
      run: ls -l
    - name: checkout the current repo
      uses: actions/checkout@v3
    - name: List my current directory after checkout
      run: ls -l